###

POST http://localhost:6006/auth/login
Content-Type: application/json

{
    "email": "rakiabodyjm@gmail.com",
    "password": "rakiabodyjm4690",
    "remember_me": false
}


###
POST http://localhost:6006/auth/protect
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4QzQwNTUtNkRGRS1FQjExLUI2NjEtMDBFMThDRUY1OTM4IiwiZW1haWwiOiJyYWtpYWJvZHlqbUBnbWFpbC5jb20iLCJmaXJzdF9uYW1lIjoiSmFuZW8gTWlndWVsIiwibGFzdF9uYW1lIjoiVGlvbmdzb24iLCJyb2xlcyI6WyJkc3AiXSwiaWF0IjoxNjI5MTc0Mjc4LCJleHAiOjE2MjkxNzc4Nzh9.W2K8bH6y5U3p_od3wwb6GvX5kEILGIxkbx_Zh637SSE
###

GET http://localhost:6006/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ4QzQwNTUtNkRGRS1FQjExLUI2NjEtMDBFMThDRUY1OTM4IiwiZW1haWwiOiJyYWtpYWJvZHlqbUBnbWFpbC5jb20iLCJmaXJzdF9uYW1lIjoiSmFuZW8gTWlndWVsIiwibGFzdF9uYW1lIjoiVGlvbmdzb24iLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE2Mjk2NTE2OTUsImV4cCI6MTYyOTY1NTI5NX0.0GA5bO2VMolRLp6pkCg5dYuQWj832b1TWXuFivEpi1g


 