
### CREATE USER
POST http://localhost:6006/user
Content-Type: application/json

{
    "first_name": "Janeo Miguel",
    "last_name": "Tiongson",
    "phone_number": "639498460475"
}
 
### SHOW ALL USERS
 GET http://localhost:6006/user/all

### CLEAR ALL USERS
 DELETE http://localhost:6006/user/clear


### GET USER BY ID
 GET http://localhost:6006/user/0F8C1FCD-ABF6-EB11-B65E-00E18CEF5938

###UPDATE USER BY ID
PATCH http://localhost:6006/user/0F8C1FCD-ABF6-EB11-B65E-00E18CEF5938
Content-Type: application/json

{
    "first_name": "Janeo",
    "last_name": "Miguel",
    "phone_number": "639498460475"
}

### DISABLE/SUSPEND USER BY ID 

PATCH http://localhost:6006/user/suspend/0F8C1FCD-ABF6-EB11-B65E-00E18CEF5938

### DELETE USER BY ID
DELETE http://localhost:6006/user/0F8C1FCD-ABF6-EB11-B65E-00E18CEF5938
