
###LOGIN FOR ADMIN ONLY
POST http://localhost:6006/auth/login
Content-Type: application/json

{
    "email": "rakiabodyjm@gmail.com", 
    "password": "rakiabodyjm4690", 
    "remember_me": true
}



### GET ALL
GET http://localhost:6006/asset


###SEARCH
GET http://localhost:6006/asset?withDeleted=true&query=hello

###
GET http://localhost:6006/asset/DFF4B5F3-2053-EC11-B66F-00E18CEF5938
###CREATE


POST http://localhost:6006/asset
Content-Type: application/json

{
    "code": "R1000", 
    "name": "DITO REGULAR SIM",     
    "description": "REALM1000 ISSUED DITO REGULAR SIM",
    "unit_price": 20.23, 
    "srp_for_subd": 23.34, 
    "srp_for_dsp": 25, 
    "srp_for_retailer": 30, 
    "srp_for_user": 40
}
###
PATCH http://localhost:6006/asset/7C9E3648-0047-EC11-B66C-00E18CEF5938
Content-Type: application/json

{
    # "code": "R1001", 
    "srp_for_subd": 1.2, 
    "approval": ["dsp", "subdistributor"]
    
    
}

###
DELETE http://localhost:6006/asset/9EED7766-BC47-EC11-B66C-00E18CEF5938

###
DELETE http://localhost:6006/asset/clear

###
DELETE http://localhost:6006/asset/soft-delete/DFF4B5F3-2053-EC11-B66F-00E18CEF5938

###SEARCH
GET http://localhost:6006/asset/search?searchQuery=DITO

### GET WITH DELETED
GET http://localhost:6006/asset?withDeleted=true