###POST
POST http://localhost:6006/request
Content-Type: application/json

{
    "amount": 5000,
    "as": "LOAN",
    "caesar_bank": "B13D3555-24D8-EC11-8CEA-00155D1CD40B"
}

###UPDATE
PATCH  http://localhost:6006/request/CCEA561F-ABF6-EC11-89A9-7085C26D3021
Content-Type: application/json

{
    "is_declined": true
}

###GET BY ID
GET http://localhost:6006/request/AD019AF5-38F4-EC11-89A8-7085C26D3021

###GET ALL
http://localhost:6006/request

###GET QUERY
http://localhost:6006/request