###POST
POST http://localhost:6006/request
Content-Type: application/json

{
    "amount": 1000,
    "as": "LOAD",
    "caesar_bank": "B13D3555-24D8-EC11-8CEA-00155D1CD40B"
}

###UPDATE
PATCH  http://localhost:6006/request/ad019af5-38f4-ec11-89a8-7085c26d3021
Content-Type: application/json

{
    "caesar_bank": "B13D3555-24D8-EC11-8CEA-00155D1CD40B"
}

###GET BY ID
GET http://localhost:6006/request/AD019AF5-38F4-EC11-89A8-7085C26D3021

###GET ALL
http://localhost:6006/request

###GET QUERY
http://localhost:6006/request