### 
GET http://localhost:6006/cash-transfer/caesar-bank



### WALLET CREDENTIALS
###


###
DELETE http://localhost:6006/cash-transfer/caesar-bank/32ACC16E-6FB6-EC11-8CCD-022002200220
### 
DELETE http://localhost:6006/cash-transfer/caesar-bank/4

###Initialize

POST http://localhost:6006/cash-transfer/caesar-bank/init

### delete all 
DELETE http://localhost:6006/cash-transfer/caesar-bank