###DEPOSIT
POST http://localhost:6006/cash-transfer/
Content-Type: application/json

{
    "transfer_type": 1, 
    "caesar_from": 
}
###
GET http://localhost:6006/cash-transfer

###
GET http://localhost:6006/cash-transfer?loan=C9D8C799-6AC0-EC11-8CD4-00155D1CD40B
###
GET http://localhost:6006/cash-transfer/79D3FAFB-26CD-EC11-8CE6-00155D1CD40B

###
# GET http://localhost:6006/cash-transfer?caesar=17FB518F-12B7-EC11-8CCD-022002200220


###LOAN PAYMENT 
POST http://localhost:6006/cash-transfer/loan-payment
Content-Type: application/json

{
    "id": "BEF8BDE2-FABA-EC11-8CD1-00155D1CD40B", 
    "amount": 3000, 
    "caesar_bank_from": "1083B7A0-28BA-EC11-8CD1-00155D1CD40B",
    "caesar_bank_to":"654E1DF0-78B9-EC11-8CD0-00155D1CD40B"

    

}

### get loan payments
GET http://localhost:6006/cash-transfer/loan-payments/A621FD61-0DC0-EC11-8CD3-00155D1CD40B

### 


POST http://localhost:6006/cash-transfer/backupData

###
POST http://localhost:6006/cash-transfer/restoreData/cash-transfer-1651856277056-staging.json

### 
GET http://localhost:6006/cash-transfer/B919034B-F1D0-EC11-8975-00155DBB6F03

### 
PATCH http://localhost:6006/cash-transfer/B919034B-F1D0-EC11-8975-00155DBB6F03
Content-Type: application/json

{

    "override_interest": 5,
    "created_at": "2022-05-01T08:58"

}

###
POST http://localhost:6006/cash-transfer/transfer
Content-Type: application/json

{
    "amount": 5000.25, 
    "as": "TRANSFER", 
    "from": "23C24E12-24CC-EC11-8CE1-00155D1CD40B", 
    "caesar_bank_to":"654E1DF0-78B9-EC11-8CD0-00155D1CD40B",
    "message":null, 
    "description":null 
}