
###
GET http://localhost:6006/cash-transfer/transfer-type

###

POST http://localhost:6006/cash-transfer/transfer-type
Content-Type: application/json

{
    "name": "PENALTY"
}

### 
POST http://localhost:6006/cash-transfer/transfer-type/init

###
DELETE http://localhost:6006/cash-transfer/transfer-type