POST http://localhost:6006/external-caesar
Content-Type: application/json

{
    "first_name": "Janeo Miguel", 
    "last_name": "Tiongson", 
    "cp_number": "09498460475", 
    "email": "rakiabodyjm@gmail.com", 
    "role": "user"
}

###
GET http://localhost:6006/external-caesar

###
DELETE http://localhost:6006/external-caesar

###
GET http://localhost:6006/external-caesar/6


###

POST http://localhost:6006/external-caesar/topup/1
Content-Type: application/json

{
    "amount": 1000
}