###POST OTP
POST http://localhost:6006/otp
Content-Type: application/json

{
    "to": "+639454067666",
    "cash_transfer": "B5C9ECE2-6E14-ED11-8CFA-00155D1CD40B"
}

###POST SMS
POST http://localhost:6006/otp/sms
Content-Type: application/json

{
   
    "from": "REALM1000",
    "to": "+639487086674",
    "request":"1C6CE1A8-F1F8-EC11-89B6-60F677E1F6FA",
    "ct_ref": "220617-LN-8F592E9854E5"
}

### PATCH
PATCH http://localhost:6006/otp/B1DAA0C4-4A28-ED11-AF1A-E86A64554969
Content-Type: application/json

{
    "verified": true
}

### VERIFY
PATCH http://localhost:6006/otp/verify/38C1B107-4C28-ED11-AF1A-E86A64554969
Content-Type: application/json

{
    "code":"520396"
}

### GET
GET http://localhost:6006/otp