### GET ADMIN ACCOUNTS

GET http://localhost:6006/admin

### CREATE NEW ADMIN
POST https://api.caesarcoin.ph/admin
Content-Type: application/json

{
    "name": "Janeo",
    "user": "B9D8E0EA-29A1-EC11-A22A-14CB6534284D"
}
###
PATCH http://localhost:6006/admin/E058BBB5-AD57-EC11-B670-00E18CEF5938
Content-Type: application/json

{
    "name": "Admin Janeo "
    # "user": null
}
###
DELETE http://localhost:6006/admin/0A03B39E-C121-EC11-B665-00E18CEF5938

### Pagination
GET http://localhost:6006/admin?page=0&limit=3

### GET 
GET http://localhost:6006/admin/0A03B39E-C121-EC11-B665-00E18CEF5938

###
GET http://localhost:6006/admin/search?searchQuery=Admin

### 
GET http://localhost:6006/