
### CREATE USER
POST http://localhost:6006/user
Content-Type: application/json

{
#    "first_name": "Janeo Miguel",
    "last_name": "Tiongson",
    "phone_number": "+639498460475",
    "password": "rakiabodyjm4690",
    "address1": "#16 General Santos Street.,Brgy. Roxas",
    "address2": null,
    "email": "rakiabodyjm@gmail.com", 
    "username": "rakiabodyjm"
    # "subdistributor":{
    #     "name": "REALM1000 SUBDISTRIBUTOR ACCOUNT", 
    #     "e_bind_number": "+639498460475", 
    #     "id_number": "123-456-789", 
    #     "zip_code": 1423, 
    #     "id_type": "LTO Driver's License", 
    #     "area_id": "2"
    # }
  
}
 
### SHOW ALL USERS
GET http://localhost:6006/user


### CLEAR ALL USERS
DELETE http://localhost:6006/user/clear
Content-Type: application/json



###sDELETE http://localhost:6006/user/E18EB353-D403-EC11-B661-00E18CEF5938
### GET USER BY ID
GET http://localhost:6006/user/EFA8FEF1-BB21-EC11-B665-00E18CEF5938
### UPDATE USER BY ID
PATCH http://localhost:6006/user/EFA8FEF1-BB21-EC11-B665-00E18CEF5938
Content-Type: application/json

{
    # "password":"rakiabodyjm4690"
    # "email":"rakiabodyjm@yahoo.com",
    # "username": "rakiabodyjm"
    # "dsp": null
    # "email": "rakiabodyjm@gmail.com",
    # "first_name": "Janeo Miguel"
    # "admin":"684A19BB-9804-EC11-B661-00E18CEF5938"
    # "dsp": "88A17787-EE06-EC11-B661-00E18CEF5938"
    # "admin": null
    # "dsp": {
    #     "dsp_code": "A-123",
    #     "area_id": 4, 
    #     "e_bind_number": "639498460475"
    # },
    
    # "email": "rakiabodyjm@gmail.com"
    # "username": "rakiabodyjm"
    "password": "rakiabodyjm4690"

}

### DISABLE/SUSPEND USER BY ID 

PATCH http://localhost:6006/user/suspend/45E069F2-CDFA-EB11-B65F-00E18CEF5938

### DELETE USER BY ID
DELETE http://localhost:6006/user/31627B95-2E32-EC11-B668-00E18CEF5938

### SEARCH
GET http://localhost:6006/user/search?find=Astrid

###Pagination
GET http://localhost:6006/user?page=0&limit=3


###
# GET http://localhost:6006/user/get-user-by-account?subdistributor=CFB5D438-BC21-EC11-B665-00E18CEF5938