
### CREATE USER
POST http://localhost:6006/user
Content-Type: application/json

{
   "first_name": "Janeo Miguel",
    "last_name": "Tiongson",
    "phone_number": "+639498460475",
    "password": "rakiabodyjm4690",
    "address1": "#16 General Santos Street.,Brgy. Roxas",
    "address2": null,
    "email": "rakiabodyjm@gmail.com",
    
    # "subdistributor":{
    #     "name": "REALM1000 SUBDISTRIBUTOR ACCOUNT", 
    #     "e_bind_number": "+639498460475", 
    #     "id_number": "123-456-789", 
    #     "zip_code": 1423, 
    #     "id_type": "LTO Driver's License", 
    #     "area_id": "2"
    # }
    # "retailer":{
    #     "store_name": "Janeo Miguel's Store",
    #     "e_bind_number": "09498460475", 
    #     "id_type": "LTO Driver's License",
    #     "id_number": "2014-14123-123T", 
    #     "subdistributor": "AF02DF31-DD2B-EC11-B666-00E18CEF5935", 
    #     "dsp": "B675433E-F36B-1410-86C5-00E785D37B7B"
    # }
    "admin":{
        "name": "Janeo"
    }
  
}
 
### SHOW ALL USERS
GET http://localhost:6006/user


### CLEAR ALL USERS
DELETE http://localhost:6006/user/clear
Content-Type: application/json



###sDELETE http://localhost:6006/user/E18EB353-D403-EC11-B661-00E18CEF5938
### GET USER BY ID
GET http://localhost:6006/user/EFA8FEF1-BB21-EC11-B665-00E18CEF5938
### UPDATE USER BY ID
PATCH http://localhost:6006/user/EFA8FEF1-BB21-EC11-B665-00E18CEF5938
Content-Type: application/json

{
    # "password":"rakiabodyjm4690"
    # "email":"rakiabodyjm@yahoo.com",
    # "username": "rakiabodyjm"
    # "dsp": null
    # "email": "rakiabodyjm@gmail.com",
    # "first_name": "Janeo Miguel"
    # "admin":"684A19BB-9804-EC11-B661-00E18CEF5938"
    # "dsp": "88A17787-EE06-EC11-B661-00E18CEF5938"
    # "admin": null
    # "dsp": {
    #     "dsp_code": "A-123",
    #     "area_id": 4, 
    #     "e_bind_number": "639498460475"
    # },
    
    # "email": "rakiabodyjm@gmail.com"
    # "username": "rakiabodyjm"
    "password": "rakiabodyjm4690"

}

### DISABLE/SUSPEND USER BY ID 

PATCH http://localhost:6006/user/suspend/45E069F2-CDFA-EB11-B65F-00E18CEF5938

### DELETE USER BY ID
DELETE http://localhost:6006/user/AE02DF31-DD2B-EC11-B666-00E18CEF5935








### SEARCH
GET http://localhost:6006/user/search?find=janeo

###Pagination
GET http://localhost:6006/user?page=0&limit=3


###
GET http://localhost:6006/user/query?admin=0A03B39E-C121-EC11-B665-00E18CEF5938