### 
GET http://localhost:6006/caesar

###aGET http://localhost:6006/caesar?page=0&limit=3

###
GET http://localhost:6006/caesar/861133C0-78B9-EC11-8CD0-00155D1CD40B
###
GET http://localhost:6006/caesar/account?dsp=7D1F2327-DB57-EC11-B670-00E18CEF5938
###
POST http://localhost:6006/caesar
Content-Type: application/json

{
    # "subdistributor": "FDC28593-B957-EC11-B670-00E18CEF5938"
    # "user": "AE02DF31-DD2B-EC11-B666-00E18CEF5935"
    "admin":"E5B9433E-F36B-1410-8214-00BFC2301278",
    # "dsp": "7D1F2327-DB57-EC11-B670-00E18CEF5938", 
    "password": "password"
    
}

###
DELETE http://localhost:6006/caesar/7FD5309C-ABCD-EC11-8CE7-00155D1CD40B


###
GET http://localhost:6006/caesar/search?searchQuery=test

###TEST-PAY

### 

POST HTTP://localhost:6006/auth/login
Content-Type: application/json

{
    "email": "rakiabodyjm", 
    "password": "rakiabodyjm4690", 
    "remember_me": true
}
###
POST http://localhost:6006/caesar/topup
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiRUZBOEZFRjEtQkIyMS1FQzExLUI2NjUtMDBFMThDRUY1OTM4IiwiZW1haWwiOiJyYWtpYWJvZHlqbSIsImZpcnN0X25hbWUiOiJNaWd1ZWwiLCJsYXN0X25hbWUiOiJUaW9uZ3NvbiIsInJvbGVzIjpbImFkbWluIiwiZHNwIiwic3ViZGlzdHJpYnV0b3IiXSwiaWF0IjoxNjQzMjA4NTI4LCJleHAiOjE2NDMyMTIxMjh9.H-aCZH73_ASgK0spLHFkTHdknO8OSVNRorkfwMNlF4s

{
    "caesar": "6120D492-245E-EC11-B672-00E18CEF5938",
    "amount": 100
}
###
GET http://localhost:6006/caesar?account_type=admin

###
### ADMIN JANEO CAESAR 3F29433E-F36B-1410-8211-00BFC2301278
PATCH http://localhost:6006/caesar/3F29433E-F36B-1410-8211-00BFC2301278
Content-Type: application/json

{
    "operator": true
}

### SEARCH V2

GET http://localhost:6006/caesar/search-v2?searchQuery=&limit=100