### 
GET http://localhost:6006/caesar

###
GET http://localhost:6006/caesar

###
GET http://localhost:6006/caesar/6120D492-245E-EC11-B672-00E18CEF5938
###
GET http://localhost:6006/caesar/account?subdistributor=FDC28593-B957-EC11-B670-00E18CEF5938
###
POST http://localhost:6006/caesar
Content-Type: application/json

{
    #"subdistributor": "CFB5D438-BC21-EC11-B665-00E18CEF5938",
    # "user": "AE02DF31-DD2B-EC11-B666-00E18CEF5935"
    "admin":"E058BBB5-AD57-EC11-B670-00E18CEF5938"
    
}

###
DELETE http://localhost:6006/caesar


###
GET http://localhost:6006/caesar/search?searchQuery= &page=0

###TEST-PAY
