### 
GET http://localhost:6006/caesar

###
GET http://localhost:6006/caesar

###
GET http://localhost:6006/caesar/BCD6AF67-AB3D-EC11-B669-00E18CEF5938
###
GET http://localhost:6006/caesar/account?subdistributor=CFB5D438-BC21-EC11-B665-00E18CEF5938
###
POST http://localhost:6006/caesar
Content-Type: application/json

{
    #"subdistributor": "CFB5D438-BC21-EC11-B665-00E18CEF5938",
    # "user": "AE02DF31-DD2B-EC11-B666-00E18CEF5935"
    "admin":"0A03B39E-C121-EC11-B665-00E18CEF5938"
    
}

###
DELETE http://localhost:6006/caesar


