
###
POST {{$dotenv REST_HOST}}/auth/login
Content-Type: application/json

{
    "email":"rakiabodyjm",
    "password": "rakiabodyjm4690",
    "remember_me":true
}
###
GET {{$dotenv REST_HOST}}/asset/
###
# POST {{$dotenv REST_HOST}}/inventory
# Content-Type: application/json

# {
#     "quantity": 100, 
#     "asset": "8A50FDA5-ED42-EC11-B66B-00E18CEF5938", 
#     "caesar": "E5CF66BA-1543-EC11-B66B-00E18CEF5938"
# }

###
POST {{$dotenv REST_HOST}}/inventory/admin-acquire
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiRUZBOEZFRjEtQkIyMS1FQzExLUI2NjUtMDBFMThDRUY1OTM4IiwiZW1haWwiOiJyYWtpYWJvZHlqbSIsImZpcnN0X25hbWUiOiJKYW5lbyBNaWd1ZWwiLCJsYXN0X25hbWUiOiJUaW9uZ3NvbiIsInJvbGVzIjpbImFkbWluIiwiZHNwIiwicmV0YWlsZXIiLCJzdWJkaXN0cmlidXRvciJdLCJpYXQiOjE2Mzg3ODI3MjIsImV4cCI6MTYzODc4MzYyMn0.FSyONHbCD-cHgwdSluYpIVBKLeqZIIvEtfEIRxa6vw0
Content-Type: application/json

{
    "quantity": 50,
    "asset" : "7C9E3648-0047-EC11-B66C-00E18CEF5938"
    
}
###
GET {{$dotenv REST_HOST}}/inventory

###
GET {{$dotenv REST_HOST}}/inventory?page=0&admin=0A03B39E-C121-EC11-B665-00E18CEF5938

###
GET {{$dotenv REST_HOST}}/inventory/CB021921-2A53-EC11-B66F-00E18CEF5938"
###


PATCH {{$dotenv REST_HOST}}/inventory/CB021921-2A53-EC11-B66F-00E18CEF5938"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiRUZBOEZFRjEtQkIyMS1FQzExLUI2NjUtMDBFMThDRUY1OTM4IiwiZW1haWwiOiJyYWtpYWJvZHlqbSIsImZpcnN0X25hbWUiOiJKYW5lbyBNaWd1ZWwiLCJsYXN0X25hbWUiOiJUaW9uZ3NvbiIsInJvbGVzIjpbImFkbWluIiwiZHNwIiwicmV0YWlsZXIiLCJzdWJkaXN0cmlidXRvciJdLCJpYXQiOjE2Mzg0MTYyNTcsImV4cCI6MTYzODQxNzE1N30.RN90B6DFYiz07c5G93fUZLQmMkX2Ens6CHf7bsXlUDs
Content-Type: application/json

{
    "quantity": 50
}

###
DELETE {{$dotenv REST_HOST}}/inventory/

### 

DELETE {{$dotenv REST_HOST}}/inventory/9EED7766-BC47-EC11-B66C-00E18CEF5938
s