
###
POST http://localhost:6006/auth/login
Content-Type: application/json

{
    "email":"rakiabodyjm",
    "password": "rakiabodyjm4690",
    "remember_me":true
}
###
GET http://localhost:6006/asset/
### s


## Accepts duplicate entry, 
## if Duplicate found
## Inventory is added
POST http://localhost:6006/inventory/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiRUZBOEZFRjEtQkIyMS1FQzExLUI2NjUtMDBFMThDRUY1OTM4IiwiZW1haWwiOiJyYWtpYWJvZHlqbSIsImZpcnN0X25hbWUiOiJNaWd1ZWwiLCJsYXN0X25hbWUiOiJUaW9uZ3NvbiIsInJvbGVzIjpbImFkbWluIiwiZHNwIiwic3ViZGlzdHJpYnV0b3IiXSwiaWF0IjoxNjQ1ODYxMjYxLCJleHAiOjE2NDU4NjQ4NjF9.hTW5VbpAid_SNoxTSY6XUyRmtsVqMExUenoLF2wi0xQ
Content-Type: application/json

{
    "quantity":50.5,
    "asset": "7C9E3648-0047-EC11-B66C-00E18CEF5938", 
    "caesar": "AC7E433E-F36B-1410-8206-00BFC2301278"
    
}
###
# GET http://localhost:6006/inventory?asset=7C9E3648-0047-EC11-B66C-00E18CEF5938

GET http://localhost:6006/inventory





###
# GET http://localhost:6006/inventory?page=0&admin=E058BBB5-AD57-EC11-B670-00E18CEF5938
GET http://localhost:6006/inventory?page=0&limit=1&admin=E058BBB5-AD57-EC11-B670-00E18CEF5938


###
GET http://localhost:6006/inventory/A57E433E-F36B-1410-8206-00BFC2301278
###


PATCH http://localhost:6006/inventory/D619FD14-98B6-EC11-8CCD-022002200220
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTZBMUQ3NDYtMDBCNy1FQzExLThDQ0QtMDIyMDAyMjAwMjIwIiwiZW1haWwiOiJyYWtpYWJvZHlqbSIsImZpcnN0X25hbWUiOiJKYW5lbyBNaWd1ZWwiLCJsYXN0X25hbWUiOiJUaW9uZ3NvbiIsInJvbGVzIjpbImFkbWluIiwiZHNwIiwic3ViZGlzdHJpYnV0b3IiXSwiYWRtaW5faWQiOiIwODlFNjVFRS0wMEI3LUVDMTEtOENDRC0wMjIwMDIyMDAyMjAiLCJkc3BfaWQiOiI0MzY1N0VDQS0xMEI3LUVDMTEtOENDRC0wMjIwMDIyMDAyMjAiLCJzdWJkaXN0cmlidXRvcl9pZCI6IkE1QjBGRDY0LTEwQjctRUMxMS04Q0NELTAyMjAwMjIwMDIyMCIsImlhdCI6MTY0OTY2OTkxMCwiZXhwIjoxNjQ5Njg0MzEwfQ.UqZeqGkR0xblZ2wj70-arD7KNdbn9MtBJqQj0g8IOLc
Content-Type: application/json

{
    # "quantity": 42, 
    # "srp_for_dsp": 1.4
    "caesar": "4A94FE3D-06B7-EC11-8CCD-022002200220"
    # "caesar":"AC7E433E-F36B-1410-8206-00BFC2301278" 
    # "unit_price":0.9
    # "description": "REALM1000 Issued Regular Load"

}

###
DELETE http://localhost:6006/inventory/

### 

DELETE http://localhost:6006/inventory/AEB9433E-F36B-1410-8214-00BFC2301278

###
GET http://localhost:6006/inventory/test-findby-asset-and-caesar
Content-Type: application/json

{
    "asset": "7C9E3648-0047-EC11-B66C-00E18CEF5938", 
    "caesar": "AE7E433E-F36B-1410-8206-00BFC2301278", 
    "hello": "world"
}


### 
GET http://localhost:6006/inventory/commerce?caesar=AE7E433E-F36B-1410-8206-00BFC2301278

###


### asset -> inventory ( Admin privilege only ) 
### to Acquire as ordinary acconut: 
###                       inventory_from, buyer
### transaction/purchase/inventory_id/caesar_id
### criteria 1:  sufficient quantity from inventory, 
### criteria 2:  sufficient caesar coin
### Response: 
### transaction | pending_transaction

### case DSP -> inventory ( which requires approval: dsp, subd ) 
### Response: 
### pending_transaction
