
###
POST http://localhost:6006/auth/login
Content-Type: application/json

{
    "email":"rakiabodyjm",
    "password": "rakiabodyjm4690",
    "remember_me":true
}
###
GET http://localhost:6006/asset/
### 

## Accepts duplicate entry, 
## if Duplicate found
## Inventory is added
POST http://localhost:6006/inventory/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiRUZBOEZFRjEtQkIyMS1FQzExLUI2NjUtMDBFMThDRUY1OTM4IiwiZW1haWwiOiJyYWtpYWJvZHlqbSIsImZpcnN0X25hbWUiOiJNaWd1ZWwiLCJsYXN0X25hbWUiOiJUaW9uZ3NvbiIsInJvbGVzIjpbImFkbWluIiwiZHNwIiwic3ViZGlzdHJpYnV0b3IiXSwiaWF0IjoxNjQwNTk5MzY2LCJleHAiOjE2NDA2MDI5NjZ9.fm9ey8IfKwwC-v9vMPBpOGQeWcPiMBnBScuqHzVmuu0
Content-Type: application/json

{
    "quantity":3,
    "asset" : "7C9E3648-0047-EC11-B66C-00E18CEF5938", 
    "caesar": "D8D04784-D65E-EC11-B672-00E18CEF5938"
    
}
###
GET http://localhost:6006/inventory


###
# GET http://localhost:6006/inventory?page=0&admin=E058BBB5-AD57-EC11-B670-00E18CEF5938
GET http://localhost:6006/inventory?page=0&subdistributor=FDC28593-B957-EC11-B670-00E18CEF5938


###
GET http://localhost:6006/inventory/9F5B433E-F36B-1410-86CD-00E785D37B7B
###


PATCH http://localhost:6006/inventory/A7CAB5D9-175F-EC11-B672-00E18CEF5938
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiRUZBOEZFRjEtQkIyMS1FQzExLUI2NjUtMDBFMThDRUY1OTM4IiwiZW1haWwiOiJyYWtpYWJvZHlqbSIsImZpcnN0X25hbWUiOiJNaWd1ZWwiLCJsYXN0X25hbWUiOiJUaW9uZ3NvbiIsInJvbGVzIjpbImFkbWluIiwiZHNwIiwic3ViZGlzdHJpYnV0b3IiXSwiaWF0IjoxNjQwNTk5MzY2LCJleHAiOjE2NDA2MDI5NjZ9.fm9ey8IfKwwC-v9vMPBpOGQeWcPiMBnBScuqHzVmuu0
Content-Type: application/json

{
    "quantity": 1000
    # "unit_price":0.9
    # "description": "REALM1000 Issued Regular Load"

}

###
DELETE http://localhost:6006/inventory/

### 

DELETE http://localhost:6006/inventory/91B5EA14-CF66-EC11-B672-00E18CEF5938