###
POST http://localhost:6006/dsp/
Content-Type: application/json

{
    "dsp_code": "John Doe DSP Account",
    "e_bind_number": "639498460473", 
    "subdistributor": "AF02DF31-DD2B-EC11-B666-00E18CEF5935",
    "user": "42AF890C-F442-EC11-B66B-00E18CEF5938", 
    "area_id": ["2"] 
}
### GET ALL DSP
GET http://localhost:6006/dsp

### GET DSP WITH ID
GET http://localhost:6006/dsp/2892E48F-C221-EC11-B665-00E18CEF5938

### DELETE ALL DSP ACCONUT
DELETE http://localhost:6006/dsp/clear
Content-Type: application/json

{
    "username" :"rakiabodyjm@gmail.com",
    "password": "rakiabodyjm4690"
}

### UPDATE DSP ACCOUNT
PATCH http://localhost:6006/dsp/2892E48F-C221-EC11-B665-00E18CEF5938
Content-Type: application/json

{
    # "dsp_code": "Breanne Testing",
    # "e_bind_number": "9931293332"
    # "user": "45E069F2-CDFA-EB11-B65F-00E18CEF5938",
    # "user": "648C4055-6DFE-EB11-B661-00E18CEF5938"
    "area_id": ["1", "2"]
    # "area_id" : null
}
###
DELETE {{$dotenv HOST}}:{{$dotenv PORT}}/dsp/65D172A9-2C21-EC11-B665-00E18CEF5938

###
GET {{$dotenv REST_HOST}}/dsp?subdistributor=CFB5D438-BC21-EC11-B665-00E18CEF5938&limit=1&page=0&countOnly=false

###SEARCH

GET {{$dotenv REST_HOST}}/dsp/search?searchQuery=arj&subdistributor=CFB5D438-BC21-EC11-B665-00E18CEF5938
###
GET {{$dotenv REST_HOST}}/dsp/search?searchQuery=jo&subdistributor=AF02DF31-DD2B-EC11-B666-00E18CEF5935
