###
POST http://localhost:6006/dsp/
Content-Type: application/json

{
    "dsp_code": "John Doe DSP Account",
    "e_bind_number": "639498460473", 
    "subdistributor": "FDC28593-B957-EC11-B670-00E18CEF5938",
    "user": "42AF890C-F442-EC11-B66B-00E18CEF5938", 
    "area_id": ["2"] 
}
### GET ALL DSP
GET http://localhost:6006/dsp

### GET DSP WITH ID
GET http://localhost:6006/dsp/02AA10C4-0F58-EC11-B670-00E18CEF5938

### DELETE ALL DSP ACCONUT
DELETE http://localhost:6006/dsp/clear
Content-Type: application/json

{
    "username" :"rakiabodyjm@gmail.com",
    "password": "rakiabodyjm4690"
}

### UPDATE DSP ACCOUNT
PATCH http://localhost:6006/dsp/C0546BF4-D558-EC11-B670-00E18CEF5938
Content-Type: application/json

{
    # "dsp_code": "Breanne Testing",
    # "e_bind_number": "9931293332"
    # "user": "45E069F2-CDFA-EB11-B65F-00E18CEF5938",
    # "user": "648C4055-6DFE-EB11-B661-00E18CEF5938"
    # "area_id": ["1", "2"]
    "dsp_code": "ANOTHER DSP"
    # "area_id" : null
}
###
DELETE {{$dotenv HOST}}:{{$dotenv PORT}}/dsp/65D172A9-2C21-EC11-B665-00E18CEF5938

###
GET http://localhost:6006/dsp?subdistributor=B2BF795F-B19E-EC11-A22A-0003FFC754C5&limit=1&page=0&countOnly=true

###SEARCH

GET http://localhost:6006/dsp/search?searchQuery=dsp&subdistributor=FDC28593-B957-EC11-B670-00E18CEF5938
###
GET http://localhost:6006/dsp/search?searchQuery=dsp

### 
PATCH http://localhost:6006/dsp/D4B9433E-F36B-1410-8214-00BFC2301278
Content-Type: application/json

{
    "user": ""
}