GET http://localhost:6006/user/
###
POST http://localhost:6006/subdistributor
Content-Type: application/json

{
    "e_bind_number": "+639498460475",
    "zip_code": "1423", 
    "id_type": "LTO Driver's License",
    "id_number":"10293-89123-2398", 
    "user": "EFA8FEF1-BB21-EC11-B665-00E18CEF5938", 
    "area_id": "1",
    "name": "REALM1000 SUBD"

}

### 
GET http://localhost:6006/subdistributor

###
GET http://localhost:6006/subdistributor/B2BF795F-B19E-EC11-A22A-0003FFC754C5
###

DELETE http://localhost:6006/subdistributor/8C7245E4-B357-EC11-B670-00E18CEF5938
###
PATCH http://localhost:6006/subdistributor/7C4FDAE3-8958-EC11-B670-00E18CEF5938
Content-Type: application/json

{
    "name": "WONG SUBD"
}
###

DELETE http://localhost:6006/subdistributor

### PAGINATION

GET http://localhost:6006/subdistributor?page=0

### SEARCH 
GET http://localhost:6006/subdistributor/search?searchQuery=Janeo
