POST http://localhost:6006/subdistributor
Content-Type: application/json

{
    "e_bind_number": "+639498460475",
    "zip_code": "1423", 
    "id_type": "LTO Driver's License",
    "id_number":"10293-89123-2398", 
    "user": "A4588092-B321-EC11-B665-00E18CEF5938", 
    "area_id": "1",
    # "user": "EFA8FEF1-BB21-EC11-B665-00E18CEF5938", 
    "name": "REALM1000 SUBD", 

}

### 
GET http://localhost:6006/subdistributor

###
GET {{$dotenv HOST}}:{{$dotenv PORT}}/subdistributor/CFB5D438-BC21-EC11-B665-00E18CEF5938
###

DELETE {{$dotenv HOST}}:{{$dotenv PORT}}/subdistributor/811642AC-E420-EC11-B665-00E18CEF5938
###
PATCH {{$dotenv HOST}}:{{$dotenv PORT}}/subdistributor/5360AFB5-4107-EC11-B661-00E18CEF5938
Content-Type: application/json

{
    "area_id": "1"
}
###

DELETE {{$dotenv REST_HOST}}/subdistributor

### PAGINATION

GET {{$dotenv REST_HOST}}/subdistributor?page=0

### SEARCH 
GET {{$dotenv REST_HOST}}/subdistributor/search?searchQuery=John Doe
